name: safe
description: safe get/set in <T extends List, Map> Object, like safe.got(data, ['key1', 'key2'])
version: 0.1.4
author: pillar<pillar@gmail.com>
homepage: https://github.com/ymzuiku/dart-safe

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

dev_dependencies:

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

# The following section is specific to Flutter.
web:


